name: Trigger dbt cloud job
on:
  pull_request:
    branches: [master]

jobs:
  prep:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
  
    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.8

    - name: Execute Test Script
      env:
        DBTCLOUDAPIKEY: ${{ secrets.DBTCLOUDAPIKEY }}
      run: |
        pip install requests
        python3 workflow.py