name: Trigger dbt cloud job
on:
  pull_request:
    branches: [master]

jobs:
  prep:
    runs-on: ubuntu-latest
    steps:
    - name: Run dbt cloud job
      run: |
        RESPONSE=$(curl -v -H "Authorization:Token ${{ secrets.DBTCLOUDAPIKEY }}" -H "Content-Type:application/json" -d '{"cause":"Triggered by Github Actions","git_branch":"master"}' https://cloud.getdbt.com/api/v2/accounts/43868/jobs/53468/run/)
        STATUSCODE=$(echo "$RESPONSE" | jq '.status.code')
        echo "$RESPONSE" | jq '.status.user_message'
        if [[ $STATUSCODE != 200 ]]; then echo "$RESPONSE" && bash -c "exit 1"; fi

    - name: Checkout
      uses: actions/checkout@v2.3.4
  
    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.8

    - name: Execute Test Script
      run: |
        pip install requests
        python3 workflow.py